version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: echo `pwd`
      - run: sudo pip3 install -r requirements.txt
      - run: sudo pip3 install gigantum
      - run: gigantum start -e

