version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt-get update && \
            sudo apt-get -y install python3 python3.6 python3.6-venv && \
            sudo apt-get -y install libxss1 libappindicator1 libindicator7 libappindicator3-1 && \
            sudo apt-get -y install xvfb && \
            sudo apt-get -y install unzip && \
            wget -N https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip && \
            unzip chromedriver_linux64.zip && chmod +x chromedriver && \
            sudo mv -f chromedriver /usr/local/share/chromedriver

      - run:
          name: Set up credentials.txt for test user (circleci)
          command: |
            echo $TEST_USERNAME > credentials.txt
            echo $TEST_PASSWORD >> credentials.txt
            cat credentials.txt

      - run:
          name: Activate virtual env and run Gigantum
          command: |
            python3.6 -m venv test-env && \
            source test-env/bin/activate && \
            pip install -r requirements.txt && \
            pip install gigantum && \
            gigantum install && \
            gigantum start && \
            sleep 10 && \
            python3 driver.py test_examples

